version: '3'

services:
  broker-service:
    build: 
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80" # 8080 is the port on the host machine, 80 is the port on the container
    deploy:
      mode: replicated
      replicas: 1