version: '3'

services:
  broker-service:
    build: 
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "3006:3000" # the port exposed by the container is 3000, but we want to access it on port 3006
    deploy:
      mode: replicated
      replicas: 1